package pass;

import java.util.ArrayList;

public class Nazione {

	ArrayList<String> nazioni = new ArrayList<>();
	
	public Nazione(){
		
		nazioni.add("Afghanistan");
		nazioni.add("Albania");
		nazioni.add("Algeria");
		nazioni.add("Andorra");
		nazioni.add("Angola");
		nazioni.add("Antigua & Deps");
		nazioni.add("Argentina");
		nazioni.add("Armenia");
		nazioni.add("Australia");
		nazioni.add("Austria");
		nazioni.add("Azerbaijan");
		nazioni.add("Bahamas");
		nazioni.add("Bahrain");
		nazioni.add("Bangladesh");
		nazioni.add("Barbados");
		nazioni.add("Belarus");
		nazioni.add("Belgium");
		nazioni.add("Belize");
		nazioni.add("Benin");
		nazioni.add("Bhutan");
		nazioni.add("Bolivia");
		nazioni.add("Bosnia Herzegovina");
		nazioni.add("Botswana");
		nazioni.add("Brazil");
		nazioni.add("Brunei");
		nazioni.add("Bulgaria");
		nazioni.add("Burkina");
		nazioni.add("Burundi");
		nazioni.add("Cambodia");
		nazioni.add("Cameroon");
		nazioni.add("Canada");
		nazioni.add("Cape Verde");
		nazioni.add("Central African Rep");
		nazioni.add("Chad");
		nazioni.add("Chile");
		nazioni.add("China");
		nazioni.add("Colombia");
		nazioni.add("Comoros");
		nazioni.add("Congo");
		nazioni.add("Congo {Democratic Rep}");
		nazioni.add("Costa Rica");
		nazioni.add("Croatia");
		nazioni.add("Cuba");
		nazioni.add("Cyprus");
		nazioni.add("Czech Republic");
		nazioni.add("Denmark");
		nazioni.add("Djibouti");
		nazioni.add("Dominica");
		nazioni.add("Dominican Republic");
		nazioni.add("East Timor");
		nazioni.add("Ecuador");
		nazioni.add("Egypt");
		nazioni.add("El Salvador");
		nazioni.add("Equatorial Guinea");
		nazioni.add("Eritrea");
		nazioni.add("Estonia");
		nazioni.add("Ethiopia");
		nazioni.add("Fiji");
		nazioni.add("Finland");
		nazioni.add("France");
		nazioni.add("Gabon");
		nazioni.add("Gambia");
		nazioni.add("Georgia");
		nazioni.add("Germany");
		nazioni.add("Ghana");
		nazioni.add("Greece");
		nazioni.add("Grenada");
		nazioni.add("Guatemala");
		nazioni.add("Guinea");
		nazioni.add("Guinea-Bissau");
		nazioni.add("Guyana");
		nazioni.add("Haiti");
		nazioni.add("Honduras");
		nazioni.add("Hungary");
		nazioni.add("Iceland");
		nazioni.add("India");
		nazioni.add("Indonesia");
		nazioni.add("Iran");
		nazioni.add("Iraq");
		nazioni.add("Ireland {Republic}");
		nazioni.add("Israel");
		nazioni.add("Italy");
		nazioni.add("Ivory Coast");
		nazioni.add("Jamaica");
		nazioni.add("Japan");
		nazioni.add("Jordan");
		nazioni.add("Kazakhstan");
		nazioni.add("Kenya");
		nazioni.add("Kiribati");
		nazioni.add("Korea North");
		nazioni.add("Korea South");
		nazioni.add("Kosovo");
		nazioni.add("Kuwait");
		nazioni.add("Kyrgyzstan");
		nazioni.add("Laos");
		nazioni.add("Latvia");
		nazioni.add("Lebanon");
		nazioni.add("Lesotho");
		nazioni.add("Liberia");
		nazioni.add("Libya");
		nazioni.add("Liechtenstein");
		nazioni.add("Lithuania");
		nazioni.add("Luxembourg");
		nazioni.add("Macedonia");
		nazioni.add("Madagascar");
		nazioni.add("Malawi");
		nazioni.add("Malaysia");
		nazioni.add("Maldives");
		nazioni.add("Mali");
		nazioni.add("Malta");
		nazioni.add("Marshall Islands");
		nazioni.add("Mauritania");
		nazioni.add("Mauritius");
		nazioni.add("Mexico");
		nazioni.add("Micronesia");
		nazioni.add("Moldova");
		nazioni.add("Monaco");
		nazioni.add("Mongolia");
		nazioni.add("Montenegro");
		nazioni.add("Morocco");
		nazioni.add("Mozambique");
		nazioni.add("Myanmar, {Burma}");
		nazioni.add("Namibia");
		nazioni.add("Nauru");
		nazioni.add("Nepal");
		nazioni.add("Netherlands");
		nazioni.add("New Zealand");
		nazioni.add("Nicaragua");
		nazioni.add("Niger");
		nazioni.add("Nigeria");
		nazioni.add("Norway");
		nazioni.add("Oman");
		nazioni.add("Pakistan");
		nazioni.add("Palau");
		nazioni.add("Panama");
		nazioni.add("Papua New Guinea");
		nazioni.add("Paraguay");
		nazioni.add("Peru");
		nazioni.add("Philippines");
		nazioni.add("Poland");
		nazioni.add("Portugal");
		nazioni.add("Qatar");
		nazioni.add("Romania");
		nazioni.add("Russian Federation");
		nazioni.add("Rwanda");
		nazioni.add("St Kitts & Nevis");
		nazioni.add("St Lucia");
		nazioni.add("Saint Vincent & the Grenadines");
		nazioni.add("Samoa");
		nazioni.add("San Marino");
		nazioni.add("Sao Tome & Principe");
		nazioni.add("Saudi Arabia");
		nazioni.add("Senegal");
		nazioni.add("Serbia");
		nazioni.add("Seychelles");
		nazioni.add("Sierra Leone");
		nazioni.add("Singapore");
		nazioni.add("Slovakia");
		nazioni.add("Slovenia");
		nazioni.add("Solomon Islands");
		nazioni.add("Somalia");
		nazioni.add("South Africa");
		nazioni.add("South Sudan");
		nazioni.add("Spain");
		nazioni.add("Sri Lanka");
		nazioni.add("Sudan");
		nazioni.add("Suriname");
		nazioni.add("Swaziland");
		nazioni.add("Sweden");
		nazioni.add("Switzerland");
		nazioni.add("Syria");
		nazioni.add("Taiwan");
		nazioni.add("Tajikistan");
		nazioni.add("Tanzania");
		nazioni.add("Thailand");
		nazioni.add("Togo");
		nazioni.add("Tonga");
		nazioni.add("Trinidad & Tobago");
		nazioni.add("Tunisia");
		nazioni.add("Turkey");
		nazioni.add("Turkmenistan");
		nazioni.add("Tuvalu");
		nazioni.add("Uganda");
		nazioni.add("Ukraine");
		nazioni.add("United Arab Emirates");
		nazioni.add("United Kingdom");
		nazioni.add("United States");
		nazioni.add("Uruguay");
		nazioni.add("Uzbekistan");
		nazioni.add("Vanuatu");
		nazioni.add("Vatican City");
		nazioni.add("Venezuela");
		nazioni.add("Vietnam");
		nazioni.add("Yemen");
		nazioni.add("Zambia");
		nazioni.add("Zimbabwe");
	}
	public String getNazione()
	{
		return nazioni.get(randBetween(0, nazioni.size()-1));
		
	}
    public int randBetween(int start, int end) {
        return start + (int)Math.round(Math.random() * (end - start));
    }
}
