/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.30
 * Generated at: 2014-05-19 10:31:43 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;
import java.util.*;
import did.*;

public final class Corsi_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			"/error.jsp", true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!--\tCorsi.jsp: \r\n");
      out.write("\tLa JSP visualizza la lista di tutti i corsi di studio attivi e gestiti da un\r\n");
      out.write("\tdiparitimento passato come parametro idDip.\r\n");
      out.write("-->\r\n");
      out.write("\r\n");
      out.write("<!-- Eseguo gli import necessari -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0 Transitional//EN\" \"http://www.w3.org/TR/REC-html40/loose.dtd\">\r\n");
 
// Genero un oggetto della classe DBMS per gestire l'interzione con la base di dati
// did2014
DBMS dbms = new DBMS();

//Ottengo l'eventuale parametro
String idDip;
if (request.getParameter("idDip") != null) // Ottengo se presente il parametro 'idDip'
	idDip = (String)request.getParameter("idDip");
else
	idDip = "";

//A seconda della presenza o meno del parametro la JSP varia il proprio comportamento
if (idDip.equals("")) {  

      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("<title>Errore!</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <div style=\" width:800px; margin:0 auto;\">\r\n");
      out.write("        <h2> SELEZIONARE PRIMA UN DIPARTIMENTO! </h2>\r\n");
      out.write("        <ul>\r\n");
      out.write("            ");
 Vector<Integer> vd = dbms.getNomiDipart(); 
      out.write("\r\n");
      out.write("            <br/><br/>\r\n");
      out.write("            ");
 for ( Integer i : vd ) { 
      out.write("\r\n");
      out.write("            <li> <a href=\"/CorsoStudi/Corsi.jsp?idDip=");
      out.print(i);
      out.write("\"> Dipartimento di ");
      out.print(dbms.getNomeDip( (int) i));
      out.write(" </a> </li>\r\n");
      out.write("            ");
 } 
      out.write("\r\n");
      out.write("        </ul>\r\n");
      out.write("    </div>\r\n");
      out.write("</body> \r\n");
      out.write("</html>\r\n");
      out.write("\r\n");

} else { 

      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("\t<title> Corsi di studi attivi </title>\r\n");
      out.write("\t<meta content=\"\">\r\n");
      out.write("\t<style></style>\r\n");
      out.write("  </head>\r\n");
      out.write("  <body>\r\n");
      out.write("\t<div>\r\n");
      out.write("\t<div>\r\n");
      out.write("\t\t<a href=\"\">\r\n");
      out.write("\t\t\t<img style=\" display:block; position: relative; top:50%; left:50%; margin-top:30px; margin-left:-30px; \" src=\"http://www.di.univr.it/documenti//Dipart/logo/logo199986.gif\">\r\n");
      out.write("\t\t</a>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<h1 style=\" font-size: 34px; color: green; text-align: center; letter-spacing: 1px;\tword-spacing: 2px;\t\" > Dipartimento di ");
      out.print( dbms.getNomeDip( Integer.parseInt(idDip) ) );
      out.write(" </h1>\r\n");
      out.write("\t<h2 style = \"text-align: center;\"> Universit&agrave degli Studi di Verona</h2>\r\n");
      out.write("\t<h3 style = \"text-align: center;\">  DIDATTICA EROGATA </h3>\r\n");
      out.write("\t<br/>\r\n");
      out.write("\t</div>\t\r\n");

	Vector<CorsoStudiBean> vcs = dbms.getCorsiDip( Integer.parseInt(idDip) );

      out.write("\t\r\n");
      out.write("\t<br/>\r\n");
      out.write("\t<br/>\r\n");
      out.write("    \r\n");
      out.write("\t");
 if ( vcs.size() > 0 ){
      out.write("\r\n");
      out.write("\t<div style=\" width:800px; margin:0 auto;\">\r\n");
      out.write("    Corsi di studio attivi gestiti dal dipartimento di ");
      out.print( dbms.getNomeDip( Integer.parseInt(idDip) ) );
      out.write(" :\r\n");
      out.write("    <br/>\r\n");
      out.write("    <br/>\r\n");
      out.write("\t");

		boolean isCs = false;
		boolean isCSLM = false;
		boolean isD = false;
		
		for ( CorsoStudiBean csb : vcs )
		{
			if ( csb.getId_tipocs() == 5 || csb.getId_tipocs() == 20 )
				isCs = true;
			else if ( csb.getId_tipocs() == 25 || csb.getId_tipocs() == 23 )
				isCSLM = true;
			else if ( csb.getId_tipocs() == 14 )
				isD = true;			
		}
		if ( isCs ){
		
      out.write("\r\n");
      out.write("\t\t\tCORSI DI LAUREA: \r\n");
      out.write("\t\t\t\t\t");
 for ( int i = 0; i<vcs.size(); i++) 
					{
						CorsoStudiBean csb =(CorsoStudiBean) vcs.get(i);
						if ( csb.getId_tipocs() == 5 || csb.getId_tipocs() == 20 ){
					
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t");
      out.print( csb.getCodice() );
      out.write(' ');
      out.write('-');
      out.write(' ');
      out.print(  csb.getNomeCorsoStudi() );
      out.write("\t\r\n");
      out.write("\t\t\t\t\t\t\t\t<li> Durata anni: ");
      out.print(  csb.getDurataanni() );
      out.write(" </li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li> Sede: ");
      out.print( csb.getSede() );
      out.write(" </li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li> Presentazione: ");
      out.print( csb.getInformativa() );
      out.write(" </li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li> Numero insegnamenti attivi nell'anno 2013/2014: ");
      out.print( csb.getNumeroInsAttivi() );
      out.write(" </li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li> Numero totale crediti erogati nell'anno 2013/2014: ");
      out.print( csb.getCreditiTot() );
      out.write(" </li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t");
 } 
      out.write("\r\n");
      out.write("\t\t\t\t\t");
 } 
      out.write("\r\n");
      out.write("\t\t");
 } if ( isCSLM ) {
      out.write("\r\n");
      out.write("\t\t\t\t\tCORSI DI LAUREA MAGISTRALE: \r\n");
      out.write("\t\t\t\t\t");
 for ( int i = 0; i<vcs.size(); i++) 
					{
						CorsoStudiBean csb =(CorsoStudiBean) vcs.get(i);
						if ( csb.getId_tipocs() == 25 || csb.getId_tipocs() == 23 ){
					
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t");
      out.print( csb.getCodice() );
      out.write(' ');
      out.write('-');
      out.write(' ');
      out.print(  csb.getNomeCorsoStudi() );
      out.write("\t\r\n");
      out.write("\t\t\t\t\t\t\t\t<li> Durata anni: ");
      out.print(  csb.getDurataanni() );
      out.write(" </li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li> Sede: ");
      out.print( csb.getSede() );
      out.write(" </li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li> Presentazione: ");
      out.print( csb.getInformativa() );
      out.write(" </li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li> Numero insegnamenti attivi nell'anno 2013/2014: ");
      out.print( csb.getNumeroInsAttivi() );
      out.write(" </li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li> Numero totale crediti erogati nell'anno 2013/2014: ");
      out.print( csb.getCreditiTot() );
      out.write(" </li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t");
 } 
      out.write("\r\n");
      out.write("\t\t\t\t\t");
 } 
      out.write("\r\n");
      out.write("\t\t");
 } if ( isD ) {
      out.write("\r\n");
      out.write("\t\t\t\t\tDOTTORATI: \r\n");
      out.write("\t\t\t\t\t");
 for ( int i = 0; i<vcs.size(); i++) 
					{
						CorsoStudiBean csb =(CorsoStudiBean) vcs.get(i);
						if ( csb.getId_tipocs() == 14 ){
					
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t");
      out.print( csb.getCodice() );
      out.write(' ');
      out.write('-');
      out.write(' ');
      out.print(  csb.getNomeCorsoStudi() );
      out.write("\t\r\n");
      out.write("\t\t\t\t\t\t\t\t<li> Durata anni: ");
      out.print(  csb.getDurataanni() );
      out.write(" </li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li> Sede: ");
      out.print( csb.getSede() );
      out.write(" </li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li> Presentazione: ");
      out.print( csb.getInformativa() );
      out.write(" </li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t");
 } 
      out.write("\r\n");
      out.write("\t\t\t\t\t");
 } 
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t");
 } 
      out.write('\r');
      out.write('\n');
      out.write('	');
}
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<a href=\"Corsi.jsp\"><font color=\"00AA00\">         <<< Back</font></a>\r\n");
 
}

      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
