package bean;

// Generated 20-lug-2014 1.26.43 by Hibernate Tools 3.4.0.CR1

/**
 * Imbarco generated by hbm2java
 */
public class Imbarco implements java.io.Serializable {

	private ImbarcoId id;
	private Posto posto;
	private Biglietto biglietto;
	private Boolean imbarcato;

	public Imbarco() {
	}

	public Imbarco(ImbarcoId id, Posto posto, Biglietto biglietto) {
		this.id = id;
		this.posto = posto;
		this.biglietto = biglietto;
	}

	public Imbarco(ImbarcoId id, Posto posto, Biglietto biglietto,
			Boolean imbarcato) {
		this.id = id;
		this.posto = posto;
		this.biglietto = biglietto;
		this.imbarcato = imbarcato;
	}

	public ImbarcoId getId() {
		return this.id;
	}

	public void setId(ImbarcoId id) {
		this.id = id;
	}

	public Posto getPosto() {
		return this.posto;
	}

	public void setPosto(Posto posto) {
		this.posto = posto;
	}

	public Biglietto getBiglietto() {
		return this.biglietto;
	}

	public void setBiglietto(Biglietto biglietto) {
		this.biglietto = biglietto;
	}

	public Boolean getImbarcato() {
		return this.imbarcato;
	}

	public void setImbarcato(Boolean imbarcato) {
		this.imbarcato = imbarcato;
	}

}
