package bean;

// Generated 20-lug-2014 1.26.43 by Hibernate Tools 3.4.0.CR1

/**
 * Imbarco generated by hbm2java
 */
public class ImbarcoBean implements java.io.Serializable {

	private ImbarcoId id;
	private PostoBean posto;
	private BigliettoBean biglietto;
	private Boolean imbarcato;

	public ImbarcoBean() {
	}

	public ImbarcoBean(ImbarcoId id, PostoBean posto, BigliettoBean biglietto) {
		this.id = id;
		this.posto = posto;
		this.biglietto = biglietto;
	}

	public ImbarcoBean(ImbarcoId id, PostoBean posto, BigliettoBean biglietto,
			Boolean imbarcato) {
		this.id = id;
		this.posto = posto;
		this.biglietto = biglietto;
		this.imbarcato = imbarcato;
	}

	public ImbarcoId getId() {
		return this.id;
	}

	public void setId(ImbarcoId id) {
		this.id = id;
	}

	public PostoBean getPosto() {
		return this.posto;
	}

	public void setPosto(PostoBean posto) {
		this.posto = posto;
	}

	public BigliettoBean getBiglietto() {
		return this.biglietto;
	}

	public void setBiglietto(BigliettoBean biglietto) {
		this.biglietto = biglietto;
	}

	public Boolean getImbarcato() {
		return this.imbarcato;
	}

	public void setImbarcato(Boolean imbarcato) {
		this.imbarcato = imbarcato;
	}

}
