/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.30
 * Generated at: 2014-05-20 16:34:02 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.io.*;
import java.util.*;
import did.*;

public final class pagina3_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");

    InfoDipBean bean = (InfoDipBean) request.getAttribute("info");
    if ( bean != null ){

      out.write("\n");
      out.write("\n");
      out.write("<html>\n");
      out.write("  <head>\n");
      out.write("\t<link rel=\"shortcut icon\" href=\"../img/favicon.ico\">\n");
      out.write("\t<link rel=\"stylesheet\" href=\"../css/comune.css\">\n");
      out.write("\t<title> Informazioni generali </title>\n");
      out.write("\t<meta content=\"\">\n");
      out.write("\t<style></style>\n");
      out.write("  </head>\n");
      out.write("  <body>\n");
      out.write("\t<div class=\"titolo\">\n");
      out.write("\t\t<div>\n");
      out.write("\t\t\t<a href=\"main?ps=info\">\n");
      out.write("\t\t\t\t<img class=\"center\" src=\"http://www.di.univr.it/documenti//Dipart/logo/logo199986.gif\">\n");
      out.write("\t\t\t</a>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<h1> Dipartimento di Informatica </h1>\n");
      out.write("\t\t<h2> Universit&agrave degli Studi di Verona</h2>\n");
      out.write("\t\t<h3>  INFORMAZIONI GENERALI </h3>\n");
      out.write("\t\t<br/>\n");
      out.write("\t</div>\t\n");
      out.write("\t\n");
      out.write("\t<div class=\"info\">\n");
      out.write("\t\t<ul style=\"width:800px;\">\n");
      out.write("\t\t\t<li>\n");
      out.write("\t\t\t\t<label>Direttore Dipartimento:</label>\n");
      out.write("\t\t\t\t<div> Prof. ");
      out.print(bean.getNome());
      out.write(' ');
      out.print(bean.getCognome());
      out.write(" </div>\n");
      out.write("\t\t\t</li>\n");
      out.write("\t\t\t<li>\n");
      out.write("\t\t\t\t<label style=\"height: 100px;\">Organi Collegiali:</label>\n");
      out.write("\t\t\t\t<div style=\"text-align:justify;\">\n");
      out.write("\t\t\t\t\t Collegio dei docenti del Dottorato in Informatica <br/>\n");
      out.write("\t\t\t\t\t Collegio Didattico di Informatica <br/>\n");
      out.write("\t\t\t\t\t Collegio Didattico di Matematica <br/>\n");
      out.write("\t\t\t\t\t Comitato Scientifico del Master Universitario in Computer game development (I livello) <br/>\n");
      out.write("\t\t\t\t\t Comitato Scientifico del Master Universitario in Digital Content Creation (I livello) <br/>\n");
      out.write("\t\t\t\t\t Consiglio del Dipartimento di Informatica \n");
      out.write("\t\t\t\t </div>\n");
      out.write("\t\t\t</li>\n");
      out.write("\t\t\t<li>\n");
      out.write("\t\t\t\t<label style=\"height: 300px;\" for=\"attivitadiricerca\">Attivit&agrave di Ricerca:</label>\n");
      out.write("\t\t\t\t<div>  Il Dipartimento di Informatica promuove numerose attivit&agrave didattiche \n");
      out.write("\t\t\t\t\t\te di ricerca basate su un continuo di competenze che vanno dalla matematica \n");
      out.write("\t\t\t\t\t\talla fisica attraverso l'informatica vista come scienze e ingegneria.\n");
      out.write("\t\t\t\t\t\tLe aree di ricerca attive sono: la matematica discreta e applicata, \n");
      out.write("\t\t\t\t\t\tl'informatica teorica, i sistemi intelligenti, i sistemi informativi, \n");
      out.write("\t\t\t\t\t\tl'ingegneria del software e la sicurezza, l'informatica applicata,\n");
      out.write("\t\t\t\t\t\ti sistemi ciberfisici e la fisica applicata e della materia.\n");
      out.write("\t\t\t\t\t\tA partire da queste competenze, il Dipartimento di Informatica ha rivolto da \n");
      out.write("\t\t\t\t\t\tsempre particolare attenzione sia alla produzione scientifica (2000 pubblicazioni \n");
      out.write("\t\t\t\t\t\tinternazionali nell'ultimo settennio), alla\tpartecipazione a progetti finanziati \n");
      out.write("\t\t\t\t\t\tda enti internazionali e nazionali (26 progetti per 7.7 milioni di euro) come \n");
      out.write("\t\t\t\t\t\tall'attivit&agrave di collaborazione con le imprese mediante ricerca applicata \n");
      out.write("\t\t\t\t\t\ta forte ricaduta tecnologica (5 spin-off, 10 brevetti, 253 progetti per 4.8 milioni di euro).\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</li>\n");
      out.write("\t\t</ul>\n");
      out.write("\t</div>\n");
      out.write("\t<div class=\"barra_bassa\"> \n");
      out.write("\t\t<ul>\n");
      out.write("\t\t\t<li>\n");
      out.write("\t\t\t\t<button  class=\"green_button\" type=\"button\" onclick=\"parent.location='main'\">Indietro</button>\n");
      out.write("\t\t\t</li>\n");
      out.write("\t\t</ul>\n");
      out.write("\t</div>\n");
      out.write("\t\n");
      out.write("  </body>\n");
      out.write("</html>\n");
}
      out.write('\n');
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
