/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.30
 * Generated at: 2014-05-22 09:13:38 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.io.*;
import java.util.*;
import did.*;

public final class pagina6_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");

    Vector<InsErogatoBean> css = ( Vector<InsErogatoBean> ) request.getAttribute("ins");

      out.write("\n");
      out.write("<html>\n");
      out.write("  <head>\n");
      out.write("\t<link rel=\"shortcut icon\" href=\"../img/favicon.ico\">\n");
      out.write("\t<link rel=\"stylesheet\" href=\"../css/comune.css\">\n");
      out.write("  </head>\n");
      out.write("\t<div class=\"titolo\">\n");
      out.write("\t\t<div>\n");
      out.write("\t\t\t<a href=\"main?ps=info\">\n");
      out.write("\t\t\t\t<img class=\"center\" src=\"http://www.di.univr.it/documenti//Dipart/logo/logo199986.gif\">\n");
      out.write("\t\t\t</a>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<h1> Dipartimento di Informatica </h1>\n");
      out.write("\t\t<h2> Universit&agrave degli Studi di Verona</h2>\n");
      out.write("\t\t<h3>  INSEGNAMENTI </h3>\n");
      out.write("\t\t<br/>\n");
      out.write("\t</div>\t\n");
      out.write("\n");
      out.write("    <body>\n");
      out.write("    ");
 if ( css == null || css.size() == 0 ) {
    
      out.write("\n");
      out.write("        Nessun insegnamento\n");
      out.write("    ");
 } else { 
      out.write("\n");
      out.write("        <div style=\" width:800px; margin:0 auto;\">\t\t\n");
      out.write("        ");
	for (int i=0; i<css.size(); i++) {
                // salvo nel bean ogni insegnamento erogato 
	            InsErogatoBean ieb =(InsErogatoBean) css.get(i);

                if( ieb.getModulo().compareTo("0") == 0){
                
      out.write("\n");
      out.write("                <ul>\n");
      out.write("                    <li>Nome   : ");
      out.print(ieb.getNomeins() );
      out.write("</li>\n");
      out.write("                    <li>Codice : ");
      out.print(ieb.getCodiceins() );
      out.write("</li>\n");
      out.write("                    <li>Crediti: ");
      out.print(ieb.getCrediti() );
      out.write("</li>   \n");
      out.write("            ");
 } else { 
      out.write("\n");
      out.write("                <ul>\n");
      out.write("                <ul>\n");
      out.write("                    <li>Nome   : ");
      out.print(ieb.getNomemodulo() );
      out.write("</li>\n");
      out.write("                    <li>Crediti: ");
      out.print(ieb.getCrediti() );
      out.write("</li>\n");
      out.write("                </ul>\n");
      out.write("           ");
 } 
      out.write("\n");
      out.write("                </ul>\n");
      out.write("        ");
 } 
      out.write("\n");
      out.write("    ");
 } 
      out.write("\n");
      out.write("        </div>\n");
      out.write("\t\t<br/>\n");
      out.write("        <br/>\n");
      out.write("\n");
      out.write("    </body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
