/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.30
 * Generated at: 2014-05-20 16:35:00 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.io.*;
import java.util.*;
import did.*;

public final class pagina4_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");

     Vector<CorsoStudiBean> vcs = (Vector<CorsoStudiBean>) request.getAttribute("corsi");
    if ( vcs != null ){

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<html>\n");
      out.write("  <head>\n");
      out.write("\t<link rel=\"shortcut icon\" href=\"../img/favicon.ico\">\n");
      out.write("\t<link rel=\"stylesheet\" href=\"../css/comune.css\">\n");
      out.write("\t<title> Corsi di studi attivi </title>\n");
      out.write("\t<meta content=\"\">\n");
      out.write("\t<style></style>\n");
      out.write("  </head>\n");
      out.write("  <body>\n");
      out.write("\t<div class=\"titolo\">\n");
      out.write("\t<div>\n");
      out.write("\t\t<a href=\"main?ps=info\">\n");
      out.write("\t\t\t<img class=\"center\" src=\"http://www.di.univr.it/documenti//Dipart/logo/logo199986.gif\">\n");
      out.write("\t\t</a>\n");
      out.write("\t</div>\n");
      out.write("\t<h1> Dipartimento di Informatica </h1>\n");
      out.write("\t<h2> Universit&agrave degli Studi di Verona</h2>\n");
      out.write("\t<h3>  DIDATTICA EROGATA </h3>\n");
      out.write("\t<br/>\n");
      out.write("\t</div>\t\n");
      out.write("\t\n");
      out.write("\t<br/><br/>\n");
      out.write("\t<div style=\" width:800px; margin:0 auto;\">\n");
      out.write("\t");

		boolean isCs = false;
		boolean isCSLM = false;
		boolean isD = false;
		
		for ( CorsoStudiBean csb : vcs )
		{
			if ( csb.getId_tipocs() == 5 || csb.getId_tipocs() == 20 )
				isCs = true;
			else if ( csb.getId_tipocs() == 25 || csb.getId_tipocs() == 23 )
				isCSLM = true;
			else if ( csb.getId_tipocs() == 14 )
				isD = true;			
		}
		if ( isCs ){
		
      out.write("\n");
      out.write("\t\t\tCORSI DI LAUREA: \n");
      out.write("\t\t\t\t\t");
 for ( int i = 0; i<vcs.size(); i++) 
					{
						CorsoStudiBean csb =(CorsoStudiBean) vcs.get(i);
						if ( csb.getId_tipocs() == 5 || csb.getId_tipocs() == 20 ){
					
      out.write("\n");
      out.write("\t\t\t\t\t\t<ul>\n");
      out.write("\t\t\t\t\t\t\t\t");
      out.print( csb.getCodice() );
      out.write(' ');
      out.write('-');
      out.write(' ');
      out.print(  csb.getNomeCorsoStudi() );
      out.write("\t\n");
      out.write("\t\t\t\t\t\t\t\t<li> Durata anni: ");
      out.print(  csb.getDurataanni() );
      out.write(" </li>\n");
      out.write("\t\t\t\t\t\t\t\t<li> Sede: ");
      out.print( csb.getSede() );
      out.write(" </li>\n");
      out.write("\t\t\t\t\t\t\t\t<li> Presentazione: ");
      out.print( csb.getInformativa() );
      out.write(" </li>\n");
      out.write("\t\t\t\t\t\t\t\t<li> Numero insegnamenti attivi nell'anno 2013/2014: ");
      out.print( csb.getNumeroInsAttivi() );
      out.write(" </li>\n");
      out.write("\t\t\t\t\t\t\t\t<li> Numero totale crediti erogati nell'anno 2013/2014: ");
      out.print( csb.getCreditiTot() );
      out.write(" </li>\n");
      out.write("                                <li> <a href=\"main?ps=ins&id=");
      out.print(csb.getId());
      out.write("\"> ELENCO INSEGNAMENTI </a> </li>\n");
      out.write("\t\t\t\t\t\t</ul>\n");
      out.write("\t\t\t\t\t\t");
 } 
      out.write("\n");
      out.write("\t\t\t\t\t");
 } 
      out.write('\n');
      out.write('	');
      out.write('	');
 } if ( isCSLM ) {
      out.write("\n");
      out.write("\t\t\t\t\tCORSI DI LAUREA MAGISTRALE: \n");
      out.write("\t\t\t\t\t");
 for ( int i = 0; i<vcs.size(); i++) 
					{
						CorsoStudiBean csb =(CorsoStudiBean) vcs.get(i);
						if ( csb.getId_tipocs() == 25 || csb.getId_tipocs() == 23 ){
					
      out.write("\n");
      out.write("\t\t\t\t\t\t<ul>\n");
      out.write("\t\t\t\t\t\t\t\t");
      out.print( csb.getCodice() );
      out.write(' ');
      out.write('-');
      out.write(' ');
      out.print(  csb.getNomeCorsoStudi() );
      out.write("\t\n");
      out.write("\t\t\t\t\t\t\t\t<li> Durata anni: ");
      out.print(  csb.getDurataanni() );
      out.write(" </li>\n");
      out.write("\t\t\t\t\t\t\t\t<li> Sede: ");
      out.print( csb.getSede() );
      out.write(" </li>\n");
      out.write("\t\t\t\t\t\t\t\t<li> Presentazione: ");
      out.print( csb.getInformativa() );
      out.write(" </li>\n");
      out.write("\t\t\t\t\t\t\t\t<li> Numero insegnamenti attivi nell'anno 2013/2014: ");
      out.print( csb.getNumeroInsAttivi() );
      out.write(" </li>\n");
      out.write("\t\t\t\t\t\t\t\t<li> Numero totale crediti erogati nell'anno 2013/2014: ");
      out.print( csb.getCreditiTot() );
      out.write(" </li>\n");
      out.write("                                <li> <a href=\"main?ps=ins&id=");
      out.print(csb.getId());
      out.write("\"> ELENCO INSEGNAMENTI </a> </li>\n");
      out.write("\t\t\t\t\t\t</ul>\n");
      out.write("\t\t\t\t\t\t");
 } 
      out.write("\n");
      out.write("\t\t\t\t\t");
 } 
      out.write('\n');
      out.write('	');
      out.write('	');
 } if ( isD ) {
      out.write("\n");
      out.write("\t\t\t\t\tDOTTORATI: \n");
      out.write("\t\t\t\t\t");
 for ( int i = 0; i<vcs.size(); i++) 
					{
						CorsoStudiBean csb =(CorsoStudiBean) vcs.get(i);
						if ( csb.getId_tipocs() == 14 ){
					
      out.write("\n");
      out.write("\t\t\t\t\t\t<ul>\n");
      out.write("\t\t\t\t\t\t\t\t");
      out.print( csb.getCodice() );
      out.write(' ');
      out.write('-');
      out.write(' ');
      out.print(  csb.getNomeCorsoStudi() );
      out.write("\t\n");
      out.write("\t\t\t\t\t\t\t\t<li> Durata anni: ");
      out.print(  csb.getDurataanni() );
      out.write(" </li>\n");
      out.write("\t\t\t\t\t\t\t\t<li> Sede: ");
      out.print( csb.getSede() );
      out.write(" </li>\n");
      out.write("\t\t\t\t\t\t\t\t<li> Presentazione: ");
      out.print( csb.getInformativa() );
      out.write(" </li>\n");
      out.write("\t\t\t\t\t\t</ul>\n");
      out.write("\t\t\t\t\t\t");
 } 
      out.write("\n");
      out.write("\t\t\t\t\t");
 } 
      out.write("\n");
      out.write("    ");
 } 
      out.write("\n");
      out.write("\t</div>\n");
      out.write("\t<div class=\"barra_bassa\"> \n");
      out.write("\t\t<ul>\n");
      out.write("\t\t\t<li>\n");
      out.write("\t\t\t\t<button  class=\"green_button\" type=\"button\" onclick=\"parent.location='main'\">Indietro</button>\n");
      out.write("\t\t\t</li>\n");
      out.write("\t\t</ul>\n");
      out.write("\t</div>\n");
      out.write("  \n");
      out.write("  </body>\n");
      out.write("</html>\n");
}
      out.write('\n');
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
