INSERT INTO tratta ( partenza, arrivo, distanza, durata ) VALUES ('Ibiza','Londra','873.3',146);
INSERT INTO tratta ( partenza, arrivo, distanza, durata ) VALUES ('Ibiza','Palma di Maiorca','79.6',38);
INSERT INTO tratta ( partenza, arrivo, distanza, durata ) VALUES ('Ibiza','Verona','79.6',38);
INSERT INTO tratta ( partenza, arrivo, distanza, durata ) VALUES ('Ibiza','Monaco','814.2',143);
INSERT INTO tratta ( partenza, arrivo, distanza, durata ) VALUES ('Ibiza','Parigi','688.9',121);
INSERT INTO tratta ( partenza, arrivo, distanza, durata ) VALUES ('Verona','Londra','658.2',120);
INSERT INTO tratta ( partenza, arrivo, distanza, durata ) VALUES ('Verona','Palma di Maiorca','658.2',120);
INSERT INTO tratta ( partenza, arrivo, distanza, durata ) VALUES ('Verona','Monaco','188.7',70);
INSERT INTO tratta ( partenza, arrivo, distanza, durata ) VALUES ('Verona','Ibiza','188.7',70);
INSERT INTO tratta ( partenza, arrivo, distanza, durata ) VALUES ('Verona','Parigi','469.3',90);
INSERT INTO tratta ( partenza, arrivo, distanza, durata ) VALUES ('Palma di Maiorca','Londra','835.1',140);
INSERT INTO tratta ( partenza, arrivo, distanza, durata ) VALUES ('Palma di Maiorca','Verona','835.1',140);
INSERT INTO tratta ( partenza, arrivo, distanza, durata ) VALUES ('Palma di Maiorca','Monaco','739.6',131);
INSERT INTO tratta ( partenza, arrivo, distanza, durata ) VALUES ('Palma di Maiorca','Ibiza','79.6',40);
INSERT INTO tratta ( partenza, arrivo, distanza, durata ) VALUES ('Palma di Maiorca','Parigi','641.9',111);
INSERT INTO tratta ( partenza, arrivo, distanza, durata ) VALUES ('Parigi','Londra','213.0',81);
INSERT INTO tratta ( partenza, arrivo, distanza, durata ) VALUES ('Parigi','Palma di Maiorca','641.9',121);
INSERT INTO tratta ( partenza, arrivo, distanza, durata ) VALUES ('Parigi','Verona','469.3',95);
INSERT INTO tratta ( partenza, arrivo, distanza, durata ) VALUES ('Parigi','Monaco','425.2',97);
INSERT INTO tratta ( partenza, arrivo, distanza, durata ) VALUES ('Parigi','Ibiza','688.9',121);
INSERT INTO tratta ( partenza, arrivo, distanza, durata ) VALUES ('Londra','Palma di Maiorca','835.1',147);
INSERT INTO tratta ( partenza, arrivo, distanza, durata ) VALUES ('Londra','Verona','658.2',122);
INSERT INTO tratta ( partenza, arrivo, distanza, durata ) VALUES ('Londra','Monaco','570.4',117);
INSERT INTO tratta ( partenza, arrivo, distanza, durata ) VALUES ('Londra','Ibiza','873.3',146);
INSERT INTO tratta ( partenza, arrivo, distanza, durata ) VALUES ('Londra','Parigi','213.0',78);
INSERT INTO tratta ( partenza, arrivo, distanza, durata ) VALUES ('Monaco','Londra','640.6',124);
INSERT INTO tratta ( partenza, arrivo, distanza, durata ) VALUES ('Monaco','Palma di Maiorca','640.6',124);
INSERT INTO tratta ( partenza, arrivo, distanza, durata ) VALUES ('Monaco','Verona','640.6',124);
INSERT INTO tratta ( partenza, arrivo, distanza, durata ) VALUES ('Monaco','Ibiza','363.7',85);
INSERT INTO tratta ( partenza, arrivo, distanza, durata ) VALUES ('Monaco','Parigi','428.4',87);
